<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mani_Bharathi_M" failures="1" tests="2" name="Test1" time="15.038" errors="0" timestamp="2024-10-13T17:36:30 IST">
  <testcase classname="InterviewPractice.Execution" name="Runner1" time="7.732"/>
  <testcase classname="InterviewPractice.Execution" name="Runner2" time="4.792">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at InterviewPractice.Execution.Runner2(Execution.java:45)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- Runner2 -->
</testsuite> <!-- Test1 -->
